### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by PinkFloyd1213** [Chatic-Gaming/DiscordNukebot#2]
Which version of python should be used?
Thanks for your works !

**Comment by Chatic-Gaming** [comment]
Python 3.5+

**Comment by PinkFloyd1213** [comment]
Oh fast ;). Ok but when I start your bot, I got  this message. Any idee ? 
![image](https://user-images.githubusercontent.com/31860086/94968920-14162080-0502-11eb-8539-7d37b298d81f.png)

**Comment by Chatic-Gaming** [comment]
You need to install discord.py
`pip install discord`

**Comment by PinkFloyd1213** [comment]
Ok all works ! Thanks for your fast reply and your work, it's perfect !!

**Comment by Umeor** [comment]
@PinkFloyd1213 @Chatic-Gaming How do you start up the bot? I put in both the token ID and prefix, now I just need to get it online.
